/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Course.view;

import Course.controller.CourseController;
import Course.controller.GradeController;
import java.awt.Color;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;
import student.controller.StudentHandler;

/**
 *
 * @author mohamed
 */
public class AddGrade extends javax.swing.JFrame {

    StudentHandler stHndlr = new StudentHandler();
    CourseController coHndlr = new CourseController();
    DefaultTableModel model = new DefaultTableModel();
    GradeController grHndllr = new GradeController();
    /**
     * Creates new form AddGrade
     */
    public AddGrade() {
        initComponents();
        showEditPannel();
        coHndlr.fillCourseJcombo(jComboBox_course); //fill comboBox by course List
        stHndlr.fillStudentJtable(jGradesStuTable, ""); //Student Table
        
        //Hide some column from the table
        HideColumn(7);
        HideColumn(6);
        HideColumn(5);
        HideColumn(4);
        HideColumn(3);
        
        //table properties:
        model = (DefaultTableModel) jGradesStuTable.getModel();
        jGradesStuTable.setRowHeight(27);
        jGradesStuTable.setShowGrid(true);
        jGradesStuTable.setGridColor(Color.yellow);
        jGradesStuTable.setSelectionBackground(Color.BLACK);
    }

    private void HideColumn(int indx)
    {
        TableColumn col = jGradesStuTable.getColumnModel().getColumn(indx);
        col.setMaxWidth(0);
        col.setMinWidth(0);
        col.setPreferredWidth(0);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        mangLayer = new javax.swing.JPanel();
        jStudentField_ID = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jDeleteButton = new javax.swing.JButton();
        jAddGradeButton = new javax.swing.JButton();
        jTextField_grades = new javax.swing.JTextField();
        jComboBox_course = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jTextField_description = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jImportButton = new javax.swing.JButton();
        mangToggleButton = new javax.swing.JToggleButton();
        jButton_Back = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jGradesStuTable = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jTextField_SearchVal = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SMS");

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));

        mangLayer.setBackground(new java.awt.Color(0, 153, 153));

        jStudentField_ID.setEditable(false);
        jStudentField_ID.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Student Id:");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Course Name:");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Grade");

        jDeleteButton.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        jDeleteButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/images/delete35.png"))); // NOI18N
        jDeleteButton.setText("Cansel");
        jDeleteButton.setToolTipText("Delete?");
        jDeleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jDeleteButtonActionPerformed(evt);
            }
        });

        jAddGradeButton.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        jAddGradeButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/images/add35(2).png"))); // NOI18N
        jAddGradeButton.setText("Add");
        jAddGradeButton.setToolTipText("Add?");
        jAddGradeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jAddGradeButtonActionPerformed(evt);
            }
        });

        jTextField_grades.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jComboBox_course.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Description");

        jTextField_description.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        javax.swing.GroupLayout mangLayerLayout = new javax.swing.GroupLayout(mangLayer);
        mangLayer.setLayout(mangLayerLayout);
        mangLayerLayout.setHorizontalGroup(
            mangLayerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mangLayerLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(mangLayerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(mangLayerLayout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jDeleteButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                        .addComponent(jAddGradeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(mangLayerLayout.createSequentialGroup()
                        .addGroup(mangLayerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(mangLayerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jStudentField_ID, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField_grades)
                            .addComponent(jComboBox_course, 0, 178, Short.MAX_VALUE)
                            .addComponent(jTextField_description))))
                .addContainerGap(52, Short.MAX_VALUE))
        );
        mangLayerLayout.setVerticalGroup(
            mangLayerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mangLayerLayout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(mangLayerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jStudentField_ID)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(63, 63, 63)
                .addGroup(mangLayerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jComboBox_course, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(mangLayerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextField_grades, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(mangLayerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTextField_description, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(65, 65, 65)
                .addGroup(mangLayerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jDeleteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jAddGradeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(70, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 28)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 51, 102));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Grades Management");

        jImportButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jImportButton.setForeground(new java.awt.Color(0, 0, 102));
        jImportButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/images/icons8-import-45.png"))); // NOI18N
        jImportButton.setText("Import");
        jImportButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jImportButtonActionPerformed(evt);
            }
        });

        mangToggleButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        mangToggleButton.setForeground(new java.awt.Color(0, 0, 102));
        mangToggleButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/images/icons8-installing-updates-45_1.png"))); // NOI18N
        mangToggleButton.setText("Manage");
        mangToggleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mangToggleButtonActionPerformed(evt);
            }
        });

        jButton_Back.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton_Back.setForeground(new java.awt.Color(0, 0, 102));
        jButton_Back.setText("Back");
        jButton_Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_BackActionPerformed(evt);
            }
        });

        jGradesStuTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "fName", "lName", "Gender", "Birthdate", "Phone", "Address", "RegisterDate"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jGradesStuTable);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 51, 102));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Enter Value To Search:");

        jTextField_SearchVal.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextField_SearchVal.setForeground(new java.awt.Color(0, 51, 102));
        jTextField_SearchVal.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField_SearchValKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField_SearchValKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField_SearchValKeyTyped(evt);
            }
        });

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("All Rights Reserved @MONO Technology");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mangLayer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(107, 107, 107)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21)
                        .addComponent(jTextField_SearchVal, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane1)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jImportButton, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(mangToggleButton, javax.swing.GroupLayout.PREFERRED_SIZE, 362, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jButton_Back, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap())))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextField_SearchVal, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(mangToggleButton, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                .addComponent(jButton_Back, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jImportButton, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel6))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(mangLayer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jDeleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jDeleteButtonActionPerformed
        this.dispose();

    }//GEN-LAST:event_jDeleteButtonActionPerformed

    private void jAddGradeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jAddGradeButtonActionPerformed
        
        if(jStudentField_ID.getText().trim().equals(""))
        {
            JOptionPane.showMessageDialog(null, "student not selected yet!!");
        }
                            //errorrrrrrrrrrrrrrr:
//        else if(grHndllr.isCourseExist(jComboBox_course.getSelectedIndex())) // &&grHndllr.isStudentGrade(Integer.valueOf(jStudentField_ID.getText()))
//        {
//            JOptionPane.showMessageDialog(null, "This Course Already Have Grade");
//        }
        else{
            int stId = Integer.valueOf(jStudentField_ID.getText());
            int corId = Integer.valueOf(coHndlr.getCourseId(jComboBox_course.getSelectedItem().toString()));
            double stdGr = Double.valueOf(jTextField_grades.getText());
            String descrp = jTextField_description.getText();
        
            //add process:
            grHndllr.insertUpdateDeleteCourse('i', stId, corId, stdGr, descrp);
            
            //clear fields:
            jStudentField_ID.setText("");
            jComboBox_course.setSelectedIndex(0);
            jTextField_grades.setText("");
            jTextField_description.setText("");
            
            try{
                ManageGrade.jGradesStuTable.setModel(new DefaultTableModel(null , new Object[]{"StudentId" , "CourseId" , "Grade" , "Description"}));
                grHndllr.fillStudentJtable(ManageGrade.jGradesStuTable); //after add >> add in manageGrade form at the same time:
            }
            catch(Exception ex){
                System.out.println("grade Added");
            }
            
            
        }
        
    }//GEN-LAST:event_jAddGradeButtonActionPerformed

    private void jImportButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jImportButtonActionPerformed
        if(jGradesStuTable.getSelectedRow() >=0)
        {
            //get student ID from selected: //
            int selRow = jGradesStuTable.getSelectedRow();
//            DefaultTableModel model = (DefaultTableModel) jGradesStuTable.getModel();
            jStudentField_ID.setText(jGradesStuTable.getValueAt(selRow, 0).toString());
        }
        else
        {
            JOptionPane.showMessageDialog(null, "Select Student First !!");
        }
    }//GEN-LAST:event_jImportButtonActionPerformed

    private void mangToggleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mangToggleButtonActionPerformed
        // TODO add your handling code here:
        showEditPannel();
    }//GEN-LAST:event_mangToggleButtonActionPerformed

    private void jButton_BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_BackActionPerformed

                this.dispose();
    }//GEN-LAST:event_jButton_BackActionPerformed

    private void jTextField_SearchValKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_SearchValKeyPressed

    }//GEN-LAST:event_jTextField_SearchValKeyPressed

    private void jTextField_SearchValKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_SearchValKeyReleased

    }//GEN-LAST:event_jTextField_SearchValKeyReleased

    private void jTextField_SearchValKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_SearchValKeyTyped

    }//GEN-LAST:event_jTextField_SearchValKeyTyped

    ////////////////////////////////////////////////////////////////////////////
     private void showEditPannel() {
       if(mangToggleButton.isSelected()){
            mangLayer.setVisible(true);
        }
        else{
            mangLayer.setVisible(false);
        }
    }
    ////////////////////////////////////////////////////////////////////////////
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddGrade.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddGrade.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddGrade.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddGrade.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddGrade().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jAddGradeButton;
    private javax.swing.JButton jButton_Back;
    private javax.swing.JComboBox<String> jComboBox_course;
    private javax.swing.JButton jDeleteButton;
    public static javax.swing.JTable jGradesStuTable;
    private javax.swing.JButton jImportButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jStudentField_ID;
    private javax.swing.JTextField jTextField_SearchVal;
    private javax.swing.JTextField jTextField_description;
    private javax.swing.JTextField jTextField_grades;
    private javax.swing.JPanel mangLayer;
    private javax.swing.JToggleButton mangToggleButton;
    // End of variables declaration//GEN-END:variables
}
