/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Course.view;

import Course.controller.CourseController;
import java.awt.Color;
import static javafx.util.Duration.hours;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import login.controller.MyFunction;
import login.view.MainForm;
import static student.view.ManageForm.jStuTable;

/**
 *
 * @author mohamed
 */
public class ManageCourse extends javax.swing.JFrame {
    CourseController coHndlr = new CourseController();
    /**
     * Creates new form ManageCourse
     */
    public ManageCourse() {
        initComponents();
        showEditPannel();
        coHndlr.fillCourseJtable(jTableCourse);
        //table properties:
        jTableCourse.setRowHeight(27);
        jTableCourse.setShowGrid(true);
        jTableCourse.setGridColor(Color.BLUE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        mangLayer = new javax.swing.JPanel();
        jCoursetField_ID = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField_CourseName = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jDeleteButton = new javax.swing.JButton();
        jAddButton = new javax.swing.JButton();
        jUpdateButton = new javax.swing.JButton();
        jSpinner1 = new javax.swing.JSpinner();
        jLabel1 = new javax.swing.JLabel();
        jImportButton = new javax.swing.JButton();
        mangToggleButton = new javax.swing.JToggleButton();
        jButton_Back = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableCourse = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SMS");

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));

        mangLayer.setBackground(new java.awt.Color(204, 255, 204));

        jCoursetField_ID.setEditable(false);
        jCoursetField_ID.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Id:");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel3.setText("Course Name:");

        jTextField_CourseName.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel4.setText("Hourse Number");

        jDeleteButton.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        jDeleteButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/images/delete35.png"))); // NOI18N
        jDeleteButton.setText("Delete");
        jDeleteButton.setToolTipText("Delete?");
        jDeleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jDeleteButtonActionPerformed(evt);
            }
        });

        jAddButton.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        jAddButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/images/add35(2).png"))); // NOI18N
        jAddButton.setText("Add");
        jAddButton.setToolTipText("Add?");
        jAddButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jAddButtonActionPerformed(evt);
            }
        });

        jUpdateButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/images/update.png"))); // NOI18N
        jUpdateButton.setText("Update");
        jUpdateButton.setToolTipText("Update?");
        jUpdateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jUpdateButtonActionPerformed(evt);
            }
        });

        jSpinner1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jSpinner1.setModel(new javax.swing.SpinnerNumberModel(5, 5, 100, 1));

        javax.swing.GroupLayout mangLayerLayout = new javax.swing.GroupLayout(mangLayer);
        mangLayer.setLayout(mangLayerLayout);
        mangLayerLayout.setHorizontalGroup(
            mangLayerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mangLayerLayout.createSequentialGroup()
                .addGroup(mangLayerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mangLayerLayout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(mangLayerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(mangLayerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField_CourseName, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jCoursetField_ID, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(mangLayerLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jDeleteButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jUpdateButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jAddButton)))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        mangLayerLayout.setVerticalGroup(
            mangLayerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mangLayerLayout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(mangLayerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jCoursetField_ID)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(62, 62, 62)
                .addGroup(mangLayerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextField_CourseName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(52, 52, 52)
                .addGroup(mangLayerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(103, 103, 103)
                .addGroup(mangLayerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jDeleteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jAddButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jUpdateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 28)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 51, 102));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Manage Course");

        jImportButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jImportButton.setForeground(new java.awt.Color(0, 0, 102));
        jImportButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/images/icons8-import-45.png"))); // NOI18N
        jImportButton.setText("Import");
        jImportButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jImportButtonActionPerformed(evt);
            }
        });

        mangToggleButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        mangToggleButton.setForeground(new java.awt.Color(0, 0, 102));
        mangToggleButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/images/icons8-installing-updates-45_1.png"))); // NOI18N
        mangToggleButton.setText("Manage");
        mangToggleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mangToggleButtonActionPerformed(evt);
            }
        });

        jButton_Back.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton_Back.setForeground(new java.awt.Color(0, 0, 102));
        jButton_Back.setText("Home");
        jButton_Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_BackActionPerformed(evt);
            }
        });

        jTableCourse.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Label", "Hours Number"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableCourse.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(jTableCourse);

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("All Rights Reserved @MONO Technology");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mangLayer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jImportButton, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                                .addComponent(mangToggleButton, javax.swing.GroupLayout.PREFERRED_SIZE, 362, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 70, Short.MAX_VALUE)
                                .addComponent(jButton_Back, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(mangToggleButton, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                .addComponent(jButton_Back, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jImportButton, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 77, Short.MAX_VALUE)
                        .addComponent(jLabel2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(mangLayer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jUpdateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jUpdateButtonActionPerformed
     
        if(jCoursetField_ID.getText().equals(""))//
        {
            JOptionPane.showMessageDialog(null, "No Student Selected yet!!");
        }
        else if(coHndlr.isCourseExist(jTextField_CourseName.getText().trim()))
        {
            JOptionPane.showMessageDialog(null, "This Course Already Exists");
        }
        else
        {                   // Not Exists: //
            int id = Integer.valueOf(jCoursetField_ID.getText().trim());
            String label = jTextField_CourseName.getText().trim();
            int hours = Integer.valueOf(jSpinner1.getValue().toString().trim());
                    
            coHndlr.insertUpdateDeleteCourse('u', id, label, hours);
                
            //clear fields: //
            jCoursetField_ID.setText("");
            jTextField_CourseName.setText("");
            jSpinner1.setValue(5);
                
            //table refresh:
            ManageCourse.jTableCourse.setModel(new DefaultTableModel(null , new Object[]{"Id" , "Label" , "Hours Number"}));
            coHndlr.fillCourseJtable(ManageCourse.jTableCourse); 
        }
    }//GEN-LAST:event_jUpdateButtonActionPerformed

    private void jAddButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jAddButtonActionPerformed
       //load addCoursForm: //
       AddCourseForm addCorForm = new AddCourseForm();
       addCorForm.setVisible(true);
       addCorForm.pack();
       addCorForm.setLocationRelativeTo(null);
       addCorForm.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_jAddButtonActionPerformed

    private void jDeleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jDeleteButtonActionPerformed
        if(jCoursetField_ID.getText().trim().equals(""))
        {
            JOptionPane.showMessageDialog(null, "No Student Selected yet!!");
        }
        else{
            int action = JOptionPane.showConfirmDialog(this, "Are you sure?");
            if(action == 0) //yes = 0 >>> confirm
            {
                int del = JOptionPane.showConfirmDialog(null, "May Related Will Be Deleted" , "Delete",JOptionPane.OK_CANCEL_OPTION,0);
                if(del == 0)
                {
                    int id = Integer.valueOf(jCoursetField_ID.getText().trim());
                    coHndlr.insertUpdateDeleteCourse('d', id, null, null);
                    
                    //clear fields: //
                    jCoursetField_ID.setText("");
                    jTextField_CourseName.setText("");
                    jSpinner1.setValue(5);
                    
                    //table refresh:
                    ManageCourse.jTableCourse.setModel(new DefaultTableModel(null , new Object[]{"Id" , "Label" , "Hours Number"}));
                    coHndlr.fillCourseJtable(ManageCourse.jTableCourse);
                
                    //update main form after delete new students
                    MainForm.coursCount_lbl.setText(" Course Count = "+Integer.toString(MyFunction.countData("course")));
                }
                  
            }
            
        }
    }//GEN-LAST:event_jDeleteButtonActionPerformed

    private void jImportButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jImportButtonActionPerformed
        if(jTableCourse.getSelectedRow() >=0)
        {
            //get student data from selected: //
            int selRow = jTableCourse.getSelectedRow();
            DefaultTableModel model = (DefaultTableModel) jTableCourse.getModel();
            jCoursetField_ID.setText(model.getValueAt(selRow, 0).toString());
            jTextField_CourseName.setText(model.getValueAt(selRow, 1).toString());
            jSpinner1.setValue(Integer.valueOf(jTableCourse.getValueAt(selRow, 2).toString())); //get the spinner value form the table:
        }
        else
        {
           JOptionPane.showMessageDialog(null, "Select Course First !!");
        }
    }//GEN-LAST:event_jImportButtonActionPerformed

    private void mangToggleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mangToggleButtonActionPerformed
        // TODO add your handling code here:
        showEditPannel();
    }//GEN-LAST:event_mangToggleButtonActionPerformed

    private void jButton_BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_BackActionPerformed

        this.dispose();
    }//GEN-LAST:event_jButton_BackActionPerformed

    ////////////////////////////////////////////////////////////////////////////
     private void showEditPannel() {
       if(mangToggleButton.isSelected()){
            mangLayer.setVisible(true);
        }
        else{
            mangLayer.setVisible(false);
        }
    }
    ////////////////////////////////////////////////////////////////////////////
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManageCourse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManageCourse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManageCourse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManageCourse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManageCourse().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jAddButton;
    private javax.swing.JButton jButton_Back;
    private javax.swing.JTextField jCoursetField_ID;
    private javax.swing.JButton jDeleteButton;
    private javax.swing.JButton jImportButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner jSpinner1;
    public static javax.swing.JTable jTableCourse;
    private javax.swing.JTextField jTextField_CourseName;
    private javax.swing.JButton jUpdateButton;
    private javax.swing.JPanel mangLayer;
    private javax.swing.JToggleButton mangToggleButton;
    // End of variables declaration//GEN-END:variables
}
