/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package login.view;

import Course.view.AddCourseForm;
import Course.view.AddGrade;
import Course.view.ManageCourse;
import Course.view.ManageGrade;
import Course.view.ShowStudentGrade;
import javax.swing.JFrame;
import student.view.AddStudentForm;
import student.view.ManageForm;
import student.view.SearchForm;

/**
 *
 * @author mohamed
 */
public class MainForm extends javax.swing.JFrame {

    /**
     * Creates new form MainForm
     */
    public MainForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        wlc_logginName = new javax.swing.JLabel();
        panelcount = new javax.swing.JPanel();
        coursCount_lbl = new javax.swing.JLabel();
        panelcount1 = new javax.swing.JPanel();
        stdntCount_lbl1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jStudentItem = new javax.swing.JMenu();
        jAddStudentItem = new javax.swing.JMenuItem();
        jManageItem = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jAddCoursItem = new javax.swing.JMenuItem();
        jMenuItem_Manage = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Student Management System-SMS");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        wlc_logginName.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        wlc_logginName.setText("Welcome <#####>");

        panelcount.setBackground(new java.awt.Color(255, 153, 153));

        coursCount_lbl.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        coursCount_lbl.setForeground(new java.awt.Color(255, 255, 255));
        coursCount_lbl.setText("Courses Count = ");

        javax.swing.GroupLayout panelcountLayout = new javax.swing.GroupLayout(panelcount);
        panelcount.setLayout(panelcountLayout);
        panelcountLayout.setHorizontalGroup(
            panelcountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelcountLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(coursCount_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );
        panelcountLayout.setVerticalGroup(
            panelcountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelcountLayout.createSequentialGroup()
                .addContainerGap(62, Short.MAX_VALUE)
                .addComponent(coursCount_lbl)
                .addGap(61, 61, 61))
        );

        panelcount1.setBackground(new java.awt.Color(0, 204, 204));

        stdntCount_lbl1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        stdntCount_lbl1.setForeground(new java.awt.Color(255, 255, 255));
        stdntCount_lbl1.setText("Student Count = ");

        javax.swing.GroupLayout panelcount1Layout = new javax.swing.GroupLayout(panelcount1);
        panelcount1.setLayout(panelcount1Layout);
        panelcount1Layout.setHorizontalGroup(
            panelcount1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelcount1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(stdntCount_lbl1, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );
        panelcount1Layout.setVerticalGroup(
            panelcount1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelcount1Layout.createSequentialGroup()
                .addContainerGap(62, Short.MAX_VALUE)
                .addComponent(stdntCount_lbl1)
                .addGap(61, 61, 61))
        );

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/images/school128.png"))); // NOI18N

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("All Rights Reserved @MONO Technology");

        jButton1.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 0, 102));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/images/find35.png"))); // NOI18N
        jButton1.setText("Find Student");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(panelcount1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 224, Short.MAX_VALUE)
                .addComponent(panelcount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(wlc_logginName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(wlc_logginName)
                    .addComponent(jButton1))
                .addGap(16, 16, 16)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 71, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelcount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelcount1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(103, 103, 103)
                .addComponent(jLabel2))
        );

        jStudentItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/images/student35.png"))); // NOI18N
        jStudentItem.setText("Student");

        jAddStudentItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/images/addstudent25.png"))); // NOI18N
        jAddStudentItem.setText("Add");
        jAddStudentItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jAddStudentItemActionPerformed(evt);
            }
        });
        jStudentItem.add(jAddStudentItem);

        jManageItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/images/managestu-25.png"))); // NOI18N
        jManageItem.setText("Manage");
        jManageItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jManageItemActionPerformed(evt);
            }
        });
        jStudentItem.add(jManageItem);

        jMenuBar1.add(jStudentItem);

        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/images/book35.png"))); // NOI18N
        jMenu1.setText("Course");

        jAddCoursItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/images/book25add.png"))); // NOI18N
        jAddCoursItem.setText("Add Course");
        jAddCoursItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jAddCoursItemActionPerformed(evt);
            }
        });
        jMenu1.add(jAddCoursItem);

        jMenuItem_Manage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/images/administrative25.png"))); // NOI18N
        jMenuItem_Manage.setText("Manage");
        jMenuItem_Manage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_ManageActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem_Manage);

        jMenuBar1.add(jMenu1);

        jMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/images/grades35.png"))); // NOI18N
        jMenu2.setText("Grades Management");

        jMenuItem3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/images/stugrade25.png"))); // NOI18N
        jMenuItem3.setText("Student Grade");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem3);

        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/images/addGrade25.png"))); // NOI18N
        jMenuItem1.setText("Add Grade");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem1);

        jMenuItem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/images/managGrade25.png"))); // NOI18N
        jMenuItem2.setText("Manage");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem2);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jAddStudentItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jAddStudentItemActionPerformed
       //load addStudentForm: //
       AddStudentForm addForm = new AddStudentForm();
       addForm.setVisible(true);
       addForm.pack();
       addForm.setLocationRelativeTo(null);
       
    }//GEN-LAST:event_jAddStudentItemActionPerformed

    private void jManageItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jManageItemActionPerformed
        //load ManageForm: //
        ManageForm mngForm = new ManageForm();
        mngForm.setVisible(true);
        mngForm.pack();
        mngForm.setLocationRelativeTo(null);
        mngForm.setExtendedState(JFrame.MAXIMIZED_BOTH); //5 maximize the screen
    }//GEN-LAST:event_jManageItemActionPerformed

    private void jAddCoursItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jAddCoursItemActionPerformed
       //load addCoursForm: //
       AddCourseForm addCorForm = new AddCourseForm();
       addCorForm.setVisible(true);
       addCorForm.pack();
       addCorForm.setLocationRelativeTo(null);
       addCorForm.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_jAddCoursItemActionPerformed

    private void jMenuItem_ManageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_ManageActionPerformed
        //load ManageCoursForm: //
       ManageCourse mngCor = new ManageCourse();
       mngCor.setVisible(true);
       mngCor.pack();
       mngCor.setLocationRelativeTo(null);
       mngCor.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
       mngCor.setExtendedState(JFrame.MAXIMIZED_BOTH);
    }//GEN-LAST:event_jMenuItem_ManageActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        //  load AddGrade Form:
        AddGrade adGrad = new AddGrade();
        adGrad.setVisible(true);
        adGrad.pack();
        adGrad.setLocationRelativeTo(null);
        adGrad.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // load ManageGrad Form:
        ManageGrade mngGrad = new ManageGrade();
        mngGrad.setVisible(true);
        mngGrad.pack();
        mngGrad.setLocationRelativeTo(null);
        mngGrad.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // load ShowStudentGrade Form:
        ShowStudentGrade showHndlr = new ShowStudentGrade();
        showHndlr.setVisible(true);
        showHndlr.pack();
        showHndlr.setLocationRelativeTo(null);
        showHndlr.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        //
        SearchForm searshForm = new SearchForm();
        searshForm.setVisible(true);
        searshForm.pack();
        searshForm.setLocationRelativeTo(null);
        searshForm.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JLabel coursCount_lbl;
    private javax.swing.JMenuItem jAddCoursItem;
    private javax.swing.JMenuItem jAddStudentItem;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenuItem jManageItem;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem_Manage;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JMenu jStudentItem;
    private javax.swing.JPanel panelcount;
    private javax.swing.JPanel panelcount1;
    public static javax.swing.JLabel stdntCount_lbl1;
    public static javax.swing.JLabel wlc_logginName;
    // End of variables declaration//GEN-END:variables
}
