/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package student.view;

import general.Common;
import java.awt.Color;
import java.text.*;
import java.util.*;

import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import login.controller.MyFunction;
import login.view.MainForm;
import static login.view.MainForm.wlc_logginName;
import login.view.loginForm;
import student.controller.StudentHandler;

/**
 *
 * @author mohamed
 */
public class ManageForm extends javax.swing.JFrame {

    loginForm logFrom = new loginForm();
    DefaultTableModel model = new DefaultTableModel();
    StudentHandler stHndlr = new StudentHandler();
    /**
     * Creates new form Manage
     */
    public ManageForm() {
        initComponents();
        
        showEditPannel();
        
        //fillStudentStageTable();
        stHndlr.fillStudentJtable(jStuTable, "");
        
        //table properties:
        jStuTable.setRowHeight(27);
        jStuTable.setShowGrid(true);
        jStuTable.setGridColor(Color.yellow);
        jStuTable.setSelectionBackground(Color.BLACK);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jStuTable = new javax.swing.JTable();
        mangToggleButton = new javax.swing.JToggleButton();
        jPanel3 = new javax.swing.JPanel();
        mangLayer = new javax.swing.JPanel();
        textField_ID = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        textField_fName = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        textField_lName = new javax.swing.JTextField();
        radio_male = new javax.swing.JRadioButton();
        radio_femele = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jDateChooserBirthDate = new com.toedter.calendar.JDateChooser();
        textField_phone = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        textArea_addrss = new javax.swing.JTextArea();
        jLabel10 = new javax.swing.JLabel();
        stageCombo = new javax.swing.JComboBox<>();
        jDeleteButton = new javax.swing.JButton();
        jAddButton = new javax.swing.JButton();
        jUpdateButton = new javax.swing.JButton();
        jImportButton = new javax.swing.JButton();
        jButton_Back = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jTextField_SearchVal = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 204, 204));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 28)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 51, 102));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Manage Student");

        jStuTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "fName", "lName", "Gender", "Birthdate", "Phone", "Address", "RegisterDate"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jStuTable.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jStuTable.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(jStuTable);

        mangToggleButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        mangToggleButton.setForeground(new java.awt.Color(0, 0, 102));
        mangToggleButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/images/icons8-installing-updates-45_1.png"))); // NOI18N
        mangToggleButton.setText("Manage");
        mangToggleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mangToggleButtonActionPerformed(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(0, 204, 204));

        mangLayer.setBackground(new java.awt.Color(0, 204, 204));

        textField_ID.setEditable(false);
        textField_ID.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Id:");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel3.setText("First Name:");

        textField_fName.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel4.setText("Last Name:");

        textField_lName.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        buttonGroup1.add(radio_male);
        radio_male.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        radio_male.setText("Male");

        buttonGroup1.add(radio_femele);
        radio_femele.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        radio_femele.setText("Femele");

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Gender:");

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("BirthDate:");

        textField_phone.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        textField_phone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textField_phoneActionPerformed(evt);
            }
        });
        textField_phone.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textField_phoneKeyTyped(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Phone:");

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Address");

        textArea_addrss.setColumns(20);
        textArea_addrss.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        textArea_addrss.setRows(5);
        jScrollPane2.setViewportView(textArea_addrss);

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Stage");

        stageCombo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        stageCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jDeleteButton.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        jDeleteButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/images/delete35.png"))); // NOI18N
        jDeleteButton.setText("Delete");
        jDeleteButton.setToolTipText("Delete?");
        jDeleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jDeleteButtonActionPerformed(evt);
            }
        });

        jAddButton.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        jAddButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/images/add35(2).png"))); // NOI18N
        jAddButton.setText("Add");
        jAddButton.setToolTipText("Add?");
        jAddButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jAddButtonActionPerformed(evt);
            }
        });

        jUpdateButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/images/update.png"))); // NOI18N
        jUpdateButton.setText("Update");
        jUpdateButton.setToolTipText("Update?");
        jUpdateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jUpdateButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout mangLayerLayout = new javax.swing.GroupLayout(mangLayer);
        mangLayer.setLayout(mangLayerLayout);
        mangLayerLayout.setHorizontalGroup(
            mangLayerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mangLayerLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(mangLayerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(mangLayerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(mangLayerLayout.createSequentialGroup()
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jDateChooserBirthDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(mangLayerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(mangLayerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(mangLayerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(mangLayerLayout.createSequentialGroup()
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(textField_phone, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, mangLayerLayout.createSequentialGroup()
                                    .addGroup(mangLayerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(mangLayerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(textField_fName, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE)
                                        .addComponent(textField_lName)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, mangLayerLayout.createSequentialGroup()
                                            .addGap(49, 49, 49)
                                            .addComponent(radio_male)
                                            .addGap(18, 18, 18)
                                            .addComponent(radio_femele))
                                        .addComponent(textField_ID, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(stageCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(mangLayerLayout.createSequentialGroup()
                        .addComponent(jDeleteButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jUpdateButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jAddButton)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        mangLayerLayout.setVerticalGroup(
            mangLayerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mangLayerLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(mangLayerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(textField_ID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(mangLayerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(textField_fName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(mangLayerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(textField_lName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(mangLayerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(radio_male)
                    .addComponent(radio_femele))
                .addGap(26, 26, 26)
                .addGroup(mangLayerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6)
                    .addComponent(jDateChooserBirthDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(mangLayerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(textField_phone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(mangLayerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, 23, Short.MAX_VALUE)
                .addGroup(mangLayerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(stageCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addGap(41, 41, 41)
                .addGroup(mangLayerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jDeleteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jAddButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jUpdateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(63, 63, 63))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mangLayer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(mangLayer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jImportButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jImportButton.setForeground(new java.awt.Color(0, 0, 102));
        jImportButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/images/icons8-import-45.png"))); // NOI18N
        jImportButton.setText("Import");
        jImportButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jImportButtonActionPerformed(evt);
            }
        });

        jButton_Back.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton_Back.setForeground(new java.awt.Color(0, 0, 102));
        jButton_Back.setText("Back");
        jButton_Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_BackActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 51, 102));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Enter Value To Search:");

        jTextField_SearchVal.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextField_SearchVal.setForeground(new java.awt.Color(0, 51, 102));
        jTextField_SearchVal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_SearchValActionPerformed(evt);
            }
        });
        jTextField_SearchVal.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField_SearchValKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField_SearchValKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField_SearchValKeyTyped(evt);
            }
        });

        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("All Rights Reserved @MONO Technology");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(116, 116, 116)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(21, 21, 21)
                                .addComponent(jTextField_SearchVal, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jImportButton)
                                        .addGap(113, 113, 113)
                                        .addComponent(mangToggleButton, javax.swing.GroupLayout.DEFAULT_SIZE, 236, Short.MAX_VALUE)
                                        .addGap(99, 99, 99)
                                        .addComponent(jButton_Back, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jScrollPane1))))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextField_SearchVal, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 399, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jImportButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(mangToggleButton, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(jButton_Back, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(86, 86, 86)
                        .addComponent(jLabel11))
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textField_phoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textField_phoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textField_phoneActionPerformed

    private void textField_phoneKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textField_phoneKeyTyped
        // Allow numbers in phone field only:
        if(!Character.isDigit(evt.getKeyChar())) //not character >> consume
        {
            evt.consume();
        }
    }//GEN-LAST:event_textField_phoneKeyTyped

    private void jDeleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jDeleteButtonActionPerformed
        //delet student >> also delete all affected or related to this student:
        //Constraint Foreign key >> on delete cascade:

        /*
        ALTER TABLE SCORE
        ADD CONSTRAINT Fk_score_student FOREIGN KEY(STUDENT_ID) 
        REFERENCES STUDENT (ID) on DELETE CASCADE;
        */

        if(textField_ID.getText().equals(""))
        {
            JOptionPane.showMessageDialog(null, "No Student Selected yet!!");
        }
        else{
            int action = JOptionPane.showConfirmDialog(this, "Are you sure?");
            if(action == 0) //yes = 0 >>> confirm
            {
                int del = JOptionPane.showConfirmDialog(null, "May Related Will Be Deleted" , "Delete!",JOptionPane.OK_CANCEL_OPTION,0);
                if(del == 0)
                {
                    int id = Integer.valueOf(textField_ID.getText());
                    stHndlr.insertUpdateDeleteStudent('d', id, null, null, null, null, null, null);
                    
                    //update main form after added new students
                    MainForm.stdntCount_lbl1.setText(" Student Count "+Integer.toString(MyFunction.countData("student")));
                    ManageForm.jStuTable.setModel(new DefaultTableModel(null , new Object[]{"Id" , "First_Name" , "Last_Name" , "Gender" , "BirthDate" , "Phone" , "Address" , "RegisterDate"})); //edited
                    stHndlr.fillStudentJtable(ManageForm.jStuTable, "");
                    
                    //clear
                    textField_fName.setText("");
                    textField_lName.setText("");
                    textField_phone.setText("");
                    textArea_addrss.setText("");
                    buttonGroup1.clearSelection();
                    jDateChooserBirthDate.setDate(null); //to clear date field:
                    textField_ID.setText("");
                }
                 
            }
            
        }
    }//GEN-LAST:event_jDeleteButtonActionPerformed

    private void jAddButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jAddButtonActionPerformed
        //load addStudentForm: //
        AddStudentForm addForm = new AddStudentForm();
        addForm.setVisible(true);
        addForm.pack();
        addForm.setLocationRelativeTo(null);
        addForm.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_jAddButtonActionPerformed

    private void mangToggleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mangToggleButtonActionPerformed
        // TODO add your handling code here:
        showEditPannel();
    }//GEN-LAST:event_mangToggleButtonActionPerformed

    private void loggingName() {
        //show login username: //
        String logged = "";
        if(Common.user.trim().length() > 0)
        {
            logged = Common.user.trim();
            wlc_logginName.setText(logged);
        }
        //return logged;
    }
    
    private void jButton_BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_BackActionPerformed

        this.dispose();
    }//GEN-LAST:event_jButton_BackActionPerformed

    private void jImportButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jImportButtonActionPerformed
       if(jStuTable.getSelectedRow() >=0)
       {
           //get a new model
           //model = (DefaultTableModel) jStuTable.getModel();
           //get student data from selected: //
           int selRow = jStuTable.getSelectedRow();
           DefaultTableModel model = (DefaultTableModel) jStuTable.getModel();
           
           textField_ID.setText(model.getValueAt(selRow, 0).toString());
           textField_fName.setText(model.getValueAt(selRow, 1).toString());
           textField_lName.setText(model.getValueAt(selRow, 2).toString());
           
           if(model.getValueAt(selRow, 3).toString().equals("Male"))
           {
               radio_male.setSelected(true);
               radio_femele.setSelected(false);
           }else{
               radio_femele.setSelected(true);
               radio_male.setSelected(false);
           }
           
           //to get Date:
           Date dt;
           try {
               dt = new SimpleDateFormat("yyyy-MM-dd").parse(model.getValueAt(selRow, 4).toString());
               jDateChooserBirthDate.setDate(dt);
           } catch (ParseException ex) {
               System.out.println("ParseException: " + ex.getMessage());
           }
           
           textField_phone.setText(model.getValueAt(selRow, 5).toString());
           textArea_addrss.setText(model.getValueAt(selRow, 6).toString());
       }
       else
       {
           JOptionPane.showMessageDialog(null, "Select Student First !!");
       }
    }//GEN-LAST:event_jImportButtonActionPerformed

    private void jTextField_SearchValKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_SearchValKeyTyped

    }//GEN-LAST:event_jTextField_SearchValKeyTyped

    private void jTextField_SearchValKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_SearchValKeyPressed
        
    }//GEN-LAST:event_jTextField_SearchValKeyPressed

    private void jTextField_SearchValKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_SearchValKeyReleased
       // to search on:
       jStuTable.setModel(new DefaultTableModel(null , new Object[]{"Id" , "Frst_Name" , "Last_Name" , "Gender" , "BirthDate" , "Phone" , "Address" , "RegisterDate"}));//edited**** //to prevenent repetation of the target value:
       stHndlr.fillStudentJtable(jStuTable, jTextField_SearchVal.getText()); //convert to lowerCAse: >> Requierd: convert other also
    }//GEN-LAST:event_jTextField_SearchValKeyReleased

     // check on the student input field: //
    public boolean verifyText()
    {
        if(textField_fName.getText().equals("") || textField_lName.getText().equals("") 
                || textField_phone.getText().equals("") || textArea_addrss.getText().equals("")
                || buttonGroup1.getSelection() == null || textField_ID.getText().equals("") || jDateChooserBirthDate.getDate() == null)
        {
            JOptionPane.showMessageDialog(null, "please, Complete The Empty Filleds First");
            return false;
        }
        //put a constrain on the date: to choose a date not higher then the current //
        else if(jDateChooserBirthDate.getDate().compareTo(new Date()) > 0)
        {
            JOptionPane.showMessageDialog(null, "Future Date Not Allowed");
            return false;
        }
        else //complete the added process:
        {
            return true;
        }
    }
    
    private void jUpdateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jUpdateButtonActionPerformed
          
        if(textField_ID.getText().equals(""))//
        {
            JOptionPane.showMessageDialog(null, "No Student Selected yet!!");
        }
        else{
       // get the input student data: //
       String fname = textField_fName.getText().trim();
       String lname = textField_lName.getText().trim();
       String phone = textField_phone.getText().trim();
       String addrss = textArea_addrss.getText().trim();
       int id = Integer.valueOf(textField_ID.getText());
       
       String gender = "";
       if(radio_male.isSelected()){
           gender = "Male";
       } else if(radio_femele.isSelected()){
           gender = "Femele";
       }
       
       if(verifyText()) //call the constrained above methode: //
       {
            SimpleDateFormat dateFormat = new SimpleDateFormat("dd-MM-yyyy");
            //get date from datechoser:
            String bdate = dateFormat.format(jDateChooserBirthDate.getDate()); //error getDate : //
           
            
                stHndlr.insertUpdateDeleteStudent('u', id, fname, lname, gender, bdate, phone, addrss);
                //after add:
                textField_fName.setText("");
                textField_lName.setText("");
                textField_phone.setText("");
                textArea_addrss.setText("");
                buttonGroup1.clearSelection();
                jDateChooserBirthDate.setDate(null); //to clear date field:
                textField_ID.setText("");
                //update main form after added new students
                MainForm.stdntCount_lbl1.setText(" Student Count "+Integer.toString(MyFunction.countData("student")));
                ManageForm.jStuTable.setModel(new DefaultTableModel(null , new Object[]{"Id" , "First_Name" , "Last_Name" , "Gender" , "BirthDate" , "Phone" , "Address" , "RegisterDate"})); //edited *****
                stHndlr.fillStudentJtable(ManageForm.jStuTable, ""); ///******
            
       }
       }
    }//GEN-LAST:event_jUpdateButtonActionPerformed

    private void jTextField_SearchValActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_SearchValActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_SearchValActionPerformed

    private void showEditPannel() {
       if(mangToggleButton.isSelected()){
            mangLayer.setVisible(true);
        }
        else{
            mangLayer.setVisible(false);
        }
    }
    
////////////////////////////////////////////////////////////////////////////////
       
    //get data of Student Stage: //
    private void fillStudentStageTable()
    {
        model = (DefaultTableModel) jStuTable.getModel();
        model.setRowCount(0); //set num of default row:
        //get student data from DB:
        Vector tableRows = stHndlr.getStudents();
        for(int i = 0; i < tableRows.size(); i++)
        {
            // element At index of (i)
            Vector row = (Vector)tableRows.get(i);
            model.addRow(row);
        }
        jStuTable.setModel(model);
        jScrollPane1.setViewportView(jStuTable);
    }
    
    ////////////////////////////////////////////////////////////////////////////
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManageForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManageForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManageForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManageForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManageForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jAddButton;
    private javax.swing.JButton jButton_Back;
    private com.toedter.calendar.JDateChooser jDateChooserBirthDate;
    private javax.swing.JButton jDeleteButton;
    private javax.swing.JButton jImportButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    public static javax.swing.JTable jStuTable;
    private javax.swing.JTextField jTextField_SearchVal;
    private javax.swing.JButton jUpdateButton;
    private javax.swing.JPanel mangLayer;
    private javax.swing.JToggleButton mangToggleButton;
    private javax.swing.JRadioButton radio_femele;
    private javax.swing.JRadioButton radio_male;
    private javax.swing.JComboBox<String> stageCombo;
    private javax.swing.JTextArea textArea_addrss;
    private javax.swing.JTextField textField_ID;
    private javax.swing.JTextField textField_fName;
    private javax.swing.JTextField textField_lName;
    private javax.swing.JTextField textField_phone;
    // End of variables declaration//GEN-END:variables
}
